;;; build-resources.lisp
;;; Генерирует src/resources.lisp из файлов в resources/

(defun read-file-to-bytes (path)
  (with-open-file (stream path :element-type '(unsigned-byte 8))
    (let ((data (make-array (file-length stream) :element-type '(unsigned-byte 8))))
      (read-sequence data stream)
      data)))

(defun read-file-to-string (path)
  (with-open-file (stream path :external-format :utf-8)
    (let* ((size (file-length stream))
           (data (make-string size))
           (pos (read-sequence data stream)))
      (subseq data 0 pos))))

(defun usb8-array-to-base64-string (bytes)
  (let ((result (make-string (* (ceiling (length bytes) 3) 4)))
        (chars "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
        (idx 0))
    (loop for i from 0 below (length bytes) by 3
          for b0 = (aref bytes i)
          for b1 = (when (< (1+ i) (length bytes)) (aref bytes (1+ i)))
          for b2 = (when (< (+ 2 i) (length bytes)) (aref bytes (+ 2 i)))
          do (setf (aref result idx) (aref chars (ash b0 -2)))
             (setf (aref result (1+ idx))
                   (aref chars (logior (ash (logand b0 3) 4)
                                       (if b1 (ash b1 -4) 0))))
             (setf (aref result (+ idx 2))
                   (if b1 (aref chars (logior (ash (logand b1 15) 2)
                                              (if b2 (ash b2 -6) 0)))
                       #\=))
             (setf (aref result (+ idx 3))
                   (if b2 (aref chars (logand b2 63)) #\=))
             (incf idx 4))
    result))

(defun build-resources ()
  (let* ((base (asdf:system-source-directory :lisper))
         (resources-dir (merge-pathnames #P"resources/" base))
         (output (merge-pathnames #P"src/resources.lisp" base))
         (logo-svg (read-file-to-string (merge-pathnames #P"logo.svg" resources-dir)))
         (favicon-bytes (read-file-to-bytes (merge-pathnames #P"favicon.svg" resources-dir)))
          (favicon-b64 (usb8-array-to-base64-string favicon-bytes))
          (jscl-js (read-file-to-string (merge-pathnames #P"jscl.js" resources-dir))))
    (with-open-file (stream output :direction :output :if-exists :supersede)
      (format stream "(in-package :lisper)~%~%")
      (format stream "(defparameter *logo-svg*~%  ~S)~%~%" logo-svg)
      (format stream "(defparameter *favicon-data-uri*~%  (concatenate 'string~%               \"data:image/svg+xml;base64,\"~%               ~S))~%" favicon-b64)
      (format stream "(defparameter *jscl-js*~%  ~S)~%" jscl-js))
    (format t "Generated ~a~%" output)))

;;; ============================================================
;;; Game sources — эмбеддинг CL-кодов игр из jscl-games/
;;; ============================================================

(defun build-game-sources ()
  (let* ((base (asdf:system-source-directory :lisper))
         (games-dir (merge-pathnames #P"jscl-games/" base))
         (output (merge-pathnames #P"src/game-sources.lisp" base))
         (games '()))
    ;; Собрать .lisp и .js файлы из jscl-games/
    (when (probe-file games-dir)
      (dolist (f (directory (merge-pathnames #P"*.lisp" games-dir)))
        (let ((name (pathname-name f))
              (source (read-file-to-string f)))
          (push (list name "cl" source) games)))
      (dolist (f (directory (merge-pathnames #P"*.js" games-dir)))
        (let ((name (pathname-name f))
              (source (read-file-to-string f)))
          (push (list name "js" source) games))))
    (setf games (nreverse games))
    ;; Записать game-sources.lisp
    (with-open-file (stream output :direction :output :if-exists :supersede)
      (format stream "(in-package :lisper)~%~%")
      (format stream ";;; Автоматически сгенерировано build-resources.lisp~%")
      (format stream ";;; Источники: jscl-games/*.{lisp,js}~%~%")
      (format stream "(defparameter *game-sources* '~%  (~%")
      (dolist (g games)
        (format stream "    (~s ~s ~s)~%" (first g) (second g) (third g)))
      (format stream "    ))~%~%")
      (format stream "(defun get-game-source (name)~%")
      (format stream "  \"Возвращает (lang . source) игры по имени.\"~%")
      (format stream "  (let ((g (assoc name *game-sources* :test #'string=)))~%")
      (format stream "    (when g (cons (second g) (third g)))))~%"))
    (format t "Generated ~a (~a games)~%" output (length games))))

;;; ============================================================
;;; Tool sources — эмбеддинг CL-кодов утилит из jscl-tools/
;;; ============================================================

(defun build-tool-sources ()
  (let* ((base (asdf:system-source-directory :lisper))
         (tools-dir (merge-pathnames #P"jscl-tools/" base))
         (output (merge-pathnames #P"src/tool-sources.lisp" base))
         (tools '()))
    (when (probe-file tools-dir)
      (dolist (f (directory (merge-pathnames #P"*.lisp" tools-dir)))
        (let ((name (pathname-name f))
              (source (read-file-to-string f)))
          ;; site.lisp и markdown.lisp — это клиентский код сайта, компилируются
          ;; отдельно в бандл /jscl-bundle/site (см. build-jscl-bundles); как
          ;; исходник для form-by-form eval (tool-source) не используются
          (unless (or (string= name "site") (string= name "markdown"))
            (push (list name "cl" source) tools)))))
    (setf tools (nreverse tools))
    (with-open-file (stream output :direction :output :if-exists :supersede)
      (format stream "(in-package :lisper)~%~%")
      (format stream ";;; Автоматически сгенерировано build-resources.lisp~%")
      (format stream ";;; Источники: jscl-tools/*.lisp~%~%")
      (format stream "(defparameter *tool-sources* '~%  (~%")
      (dolist (t- tools)
        (format stream "    (~s ~s ~s)~%" (first t-) (second t-) (third t-)))
      (format stream "    ))~%~%")
      (format stream "(defun get-tool-source (name)~%")
      (format stream "  \"Возвращает (lang . source) утилиты по имени.\"~%")
      (format stream "  (let ((g (assoc name *tool-sources* :test #'string=)))~%")
      (format stream "    (when g (cons (second g) (third g)))))~%"))
    (format t "Generated ~a (~a tools)~%" output (length tools))))

;;; ============================================================
;;; Migrations — эмбеддинг SQL-файлов из migrations/
;;; ============================================================

(defun parse-migration-version (filename)
  "Извлекает version и direction из имени файла типа 0001-initial-schema.up.sql"
  (let* ((name (pathname-name filename))
         (dir-position (search ".up" name))
         (direction (if dir-position :up :down))
         (base-name (if dir-position
                        (subseq name 0 dir-position)
                        (subseq name 0 (- (length name) (length ".down"))))))
    (let ((dash-pos (position #\- base-name)))
      (when dash-pos
        (values (parse-integer (subseq base-name 0 dash-pos))
                direction)))))

(defun build-migrations ()
  (let* ((base (asdf:system-source-directory :lisper))
         (migrations-dir (merge-pathnames #P"migrations/" base))
         (output (merge-pathnames #P"src/migrations.lisp" base))
         (migrations (make-hash-table)))
    (when (probe-file migrations-dir)
      (dolist (f (directory (merge-pathnames #P"*.sql" migrations-dir)))
        (multiple-value-bind (version direction) (parse-migration-version (file-namestring f))
          (when (and version direction)
            (let ((sql (read-file-to-string f)))
              (unless (gethash version migrations)
                (setf (gethash version migrations) (make-hash-table)))
              (setf (gethash direction (gethash version migrations)) sql))))))
    ;; Собрать отсортированный список версий
    (let ((versions (sort (loop for k being the hash-keys of migrations collect k) #'<)))
      (with-open-file (stream output :direction :output :if-exists :supersede)
        (format stream "(in-package :lisper)~%~%")
        (format stream ";;; Embedded migration SQL files~%")
        (format stream ";;; Generated from migrations/*.sql — do not edit manually~%~%")
        (format stream "(defvar *migrations*~%  '(")
        (dolist (v versions)
          (let ((dirs (gethash v migrations)))
            (format stream "~%    (~A . ((:up . ~S)~%" v (gethash :up dirs))
            (format stream "          (:down . ~S)))" (gethash :down dirs))))
        (format stream "))~%~%")
        (format stream "(defun get-available-migrations ()~%")
        (format stream "  \"Return sorted list of (version name) from embedded migrations.\"~%")
        (format stream "  (sort (mapcar (lambda (entry)~%")
        (format stream "                  (list (car entry)~%")
        (format stream "                        (format nil \"migration-~~A\" (car entry))))~%")
        (format stream "                *migrations*)~%")
        (format stream "        #'< :key #'first))~%~%")
        (format stream "(defun get-migration-sql (version direction)~%")
        (format stream "  \"Get SQL for a migration version and direction (:up or :down).\"~%")
        (format stream "  (let ((entry (assoc version *migrations*)))~%")
        (format stream "    (when entry~%")
        (format stream "      (cdr (assoc direction (cdr entry))))))~%"))
      (format t "Generated ~a (~a migrations)~%" output (length versions)))))

;;; ============================================================
;;; JSCL bundles — компиляция jscl-tools/ и jscl-games/ в JS
;;; через node (jscl/jscl-node.js) и эмбеддинг в jscl-bundles.lisp
;;; ============================================================

(defun node-available-p ()
  "T when the node binary is runnable (build step uses it to compile bundles)."
  (handler-case
      (multiple-value-bind (_out _err code)
          (uiop:run-program (list "node" "--version")
                            :output :string :error-output :string
                            :ignore-error-status t)
        (declare (ignore _out _err))
        (zerop code))
    (error () nil)))

(defun file-sha256-hex (path)
  "SHA-256 hex файла через node crypto (совпадает с ironclad hex в рантайме)."
  (multiple-value-bind (out _err code)
      (uiop:run-program
       (list "node" "-e"
             (format nil "const fs=require('fs'),c=require('crypto');process.stdout.write(c.createHash('sha256').update(fs.readFileSync(~s)).digest('hex'))"
                     (namestring path)))
       :output :string :error-output :string :ignore-error-status t)
    (declare (ignore _err))
    (when (and (zerop code) out)
      (string-trim '(#\Newline #\Space #\Tab) out))))

(defun write-site-prelude (build-dir hashes)
  "Пишет прелюдию для site-бандла: (defpackage :site ...) + *site-bundle-urls*.
   Возвращает путь к прелюдии."
  (let ((prelude (merge-pathnames #P"site-prelude.lisp" build-dir)))
    (with-open-file (stream prelude :direction :output :if-exists :supersede)
      (format stream ";;; Автоген. build-resources.lisp — прелюдия site-бандла~%")
      (format stream "(defpackage :site (:use :cl) (:import-from :jscl/ffi))~%")
      (format stream "(in-package :site)~%~%")
      (format stream "(defparameter *site-bundle-urls*~%  '(")
      (dolist (name '("repl" "lisp-invaders" "lambda-runner" "paren-matcher" "s-dungeon"))
        (let ((hash (gethash name hashes)))
          (when hash
            (format stream "~%    (~s . ~s)"
                    name (format nil "/jscl-bundle/~a?v=~a" name hash)))))
      (format stream "~%    ))~%"))
    prelude))

(defun build-jscl-bundles ()
  "Compile jscl-tools/*.lisp and jscl-games/*.lisp into JS bundles with node,
   then embed them in src/jscl-bundles.lisp. No-op (empty table) without node."
  (let* ((base (asdf:system-source-directory :lisper))
         (tools-dir (merge-pathnames #P"jscl-tools/" base))
         (games-dir (merge-pathnames #P"jscl-games/" base))
         (build-dir (merge-pathnames #P"build/jscl-bundles/" base))
         (script-path (merge-pathnames #P"build/compile-apps.lisp" base))
         (compiler (merge-pathnames #P"jscl/jscl-node.js" base))
         (output (merge-pathnames #P"src/jscl-bundles.lisp" base))
         (sources '()))
    (dolist (d (list tools-dir games-dir))
      (when (probe-file d)
        (dolist (f (directory (merge-pathnames #P"*.lisp" d)))
          ;; site.lisp и markdown.lisp компилируются отдельно вместе с прелюдией (см. ниже)
          (unless (or (string= (pathname-name f) "site")
                      (string= (pathname-name f) "markdown"))
            (push (list (pathname-name f) (namestring f)) sources)))))
    (setf sources (sort sources #'string< :key #'first))
    (ensure-directories-exist build-dir)
    (ensure-directories-exist (merge-pathnames #P"build/" base))
    (let ((bundles '())
          (node-ok nil))
      (when (node-available-p)
        (setf node-ok t)
        (with-open-file (stream script-path :direction :output :if-exists :supersede)
          (format stream "(dolist (spec '(")
          (dolist (s sources)
            (format stream "~%  (~s . ~s)" (first s) (second s)))
          (format stream "~%  ))~%")
          (format stream "  (jscl:compile-application~%")
          (format stream "    (list (cdr spec))~%")
          (format stream "    (concatenate 'string ~s (car spec) ~s)~%"
                  (namestring build-dir) ".js")
          (format stream "    :place \"\" :jscl-name \"jscl\")~%")
          (format stream "    (format t \"~~&BUNDLE-OK: ~~a~~%\" (car spec)))~%"))
        (multiple-value-bind (_out err code)
            (uiop:run-program
             (list "node" "--stack-size=65536"
                   (namestring compiler) (namestring script-path))
             :output :string :error-output :string :ignore-error-status t)
          (declare (ignore _out))
          (unless (zerop code)
            (format t "~&WARNING: jscl bundle compile failed (code ~a): ~a~%" code err)))
        (dolist (s sources)
          (let ((bundle (merge-pathnames (format nil "~a.js" (first s)) build-dir)))
            (if (probe-file bundle)
                (push (list (first s) (read-file-to-string bundle)) bundles)
                (format t "~&WARNING: bundle ~a was not produced~%" (first s)))))
        ;; --- Site bundle: прелюдия (*site-bundle-urls*) + jscl-tools/site.lisp ---
        (let ((site-src (merge-pathnames #P"jscl-tools/site.lisp" base))
              (md-src (merge-pathnames #P"jscl-tools/markdown.lisp" base)))
          (when (probe-file site-src)
            (let ((hashes (make-hash-table :test #'equal)))
              (dolist (name '("repl" "lisp-invaders" "lambda-runner" "paren-matcher" "s-dungeon"))
                (let ((bundle (merge-pathnames (format nil "~a.js" name) build-dir)))
                  (when (probe-file bundle)
                    (setf (gethash name hashes) (file-sha256-hex bundle)))))
              (let ((prelude (write-site-prelude build-dir hashes))
                    (site-out (merge-pathnames #P"site.js" build-dir))
                    (site-compile (merge-pathnames #P"build/compile-site.lisp" base)))
                (with-open-file (stream site-compile :direction :output :if-exists :supersede)
                  (format stream "(jscl:compile-application~%")
                  (format stream "  (list ~s" (namestring prelude))
                  (format stream "~%        ~s" (namestring md-src))
                  (format stream "~%        ~s)~%" (namestring site-src))
                  (format stream "  ~s~%" (namestring site-out))
                  (format stream "  :place \"\" :jscl-name \"jscl\")~%"))
                (multiple-value-bind (_out err code)
                    (uiop:run-program
                     (list "node" "--stack-size=65536"
                           (namestring compiler) (namestring site-compile))
                     :output :string :error-output :string :ignore-error-status t)
                  (declare (ignore _out))
                  (unless (zerop code)
                    (format t "~&WARNING: site bundle compile failed (code ~a): ~a~%" code err)))
                (when (probe-file site-out)
                  (push (list "site" (read-file-to-string site-out)) bundles)
                  (format t "~&BUNDLE-OK: site~%")))))))
      (setf bundles (nreverse bundles))
      (with-open-file (stream output :direction :output :if-exists :supersede)
        (format stream "(in-package :lisper)~%~%")
        (format stream ";;; Автоматически сгенерировано build-resources.lisp~%")
        (format stream ";;; JS-бандлы игр/тулзов, скомпилированные node-ом из jscl-tools/, jscl-games/~%~%")
        (format stream "(defparameter *jscl-bundles*~%  '(")
        (dolist (b bundles)
          (format stream "~%    (~s . ~s)" (first b) (second b)))
        (format stream "~%    ))~%~%")
        (format stream "(defun get-jscl-bundle (name)~%")
        (format stream "  \"Возвращает JS-бандл по имени.\"~%")
        (format stream "  (cdr (assoc name *jscl-bundles* :test #'string=)))~%"))
      (format t "Generated ~a (~a bundles, node=~a)~%" output (length bundles)
              (if node-ok "yes" "NO")))))

(build-resources)
(build-game-sources)
(build-tool-sources)
(build-migrations)
(build-jscl-bundles)
(quit)
