global.self = global; global.window = global;
const jscl = require('/home/turtle/lisper-site/jscl/jscl.js');
global.jscl = jscl;
const fs = require('fs');
new Function(fs.readFileSync(process.env.BUNDLE || '/tmp/md_iter6.js','utf8'))();
const md = jscl.packages['MARKDOWN'].symbols;
const clstr = s => jscl.internals.make_lisp_string(s);
const render = md['RENDER-TO-HTML'].fvalue;
function toStr(x) {
  if (x === null || x === undefined) return '';
  if (typeof x === 'string') return x;
  if (Array.isArray(x)) return x.map(toStr).join('');
  if (x.string !== undefined) return x.string;
  if (x.$$jscl_car !== undefined) return toStr(x.$$jscl_car)+toStr(x.$$jscl_cdr);
  return String(x);
}
const cases = [
  ['*foo bar*', '<p><em>foo bar</em></p>', 350],
  ['a * foo bar*', '<p>a * foo bar*</p>', 351],
  ['a*"foo"*', '<p>a*&quot;foo&quot;*</p>', 352],
  ['* a *', '<p>* a *</p>', 353],
  ['*$*alpha.\n\n*£*bravo.\n\n*€*charlie.', '<p>*$*alpha.</p>\n<p>*£*bravo.</p>\n<p>*€*charlie.</p>', 354],
  ['foo*bar*', '<p>foo<em>bar</em></p>', 355],
  ['5*6*78', '<p>5<em>6</em>78</p>', 356],
  ['_foo bar_', '<p><em>foo bar</em></p>', 357],
  ['_ foo bar_', '<p>_ foo bar_</p>', 358],
  ['a_"foo"_', '<p>a_&quot;foo&quot;_</p>', 359],
  ['foo_bar_', '<p>foo_bar_</p>', 360],
  ['5_6_78', '<p>5_6_78</p>', 361],
  ['пристаням_стремятся_', '<p>пристаням_стремятся_</p>', 362],
  ['aa_"bb"_cc', '<p>aa_&quot;bb&quot;_cc</p>', 363],
  ['foo-_(bar)_', '<p>foo-<em>(bar)</em></p>', 364],
  ['_foo*', '<p>_foo*</p>', 365],
  ['*foo bar *', '<p>*foo bar *</p>', 366],
  ['*foo bar\n*', '<p>*foo bar\n*</p>', 367],
  ['*(*foo)', '<p>*(*foo)</p>', 368],
  ['*(*foo*)*', '<p><em>(<em>foo</em>)</em></p>', 369],
  ['*foo*bar', '<p><em>foo</em>bar</p>', 370],
  ['_foo bar _', '<p>_foo bar _</p>', 371],
  ['_(_foo)', '<p>_(_foo)</p>', 372],
  ['_(_foo_)_', '<p><em>(<em>foo</em>)</em></p>', 373],
  ['_foo_bar', '<p>_foo_bar</p>', 374],
  ['_пристаням_стремятся', '<p>_пристаням_стремятся</p>', 375],
  ['_foo_bar_baz_', '<p><em>foo_bar_baz</em></p>', 376],
  ['_(bar)_.', '<p><em>(bar)</em>.</p>', 377],
  ['**foo bar**', '<p><strong>foo bar</strong></p>', 378],
  ['** foo bar**', '<p>** foo bar**</p>', 379],
  ['a**"foo"**', '<p>a**&quot;foo&quot;**</p>', 380],
  ['foo**bar**', '<p>foo<strong>bar</strong></p>', 381],
  ['__foo bar__', '<p><strong>foo bar</strong></p>', 382],
  ['__ foo bar__', '<p>__ foo bar__</p>', 383],
  ['__\nfoo bar__', '<p>__\nfoo bar__</p>', 384],
  ['a__"foo"__', '<p>a__&quot;foo&quot;__</p>', 385],
  ['foo__bar__', '<p>foo__bar__</p>', 386],
  ['5__6__78', '<p>5__6__78</p>', 387],
  ['пристаням__стремятся__', '<p>пристаням__стремятся__</p>', 388],
  ['__foo, __bar__, baz__', '<p><strong>foo, <strong>bar</strong>, baz</strong></p>', 389],
  ['foo-__(bar)__', '<p>foo-<strong>(bar)</strong></p>', 390],
  ['**foo bar **', '<p>**foo bar **</p>', 391],
  ['**(**foo)', '<p>**(**foo)</p>', 392],
  ['*(**foo**)*', '<p><em>(<strong>foo</strong>)</em></p>', 393],
  ['**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**', '<p><strong>Gomphocarpus (<em>Gomphocarpus physocarpus</em>, syn.\n<em>Asclepias physocarpa</em>)</strong></p>', 394],
  ['**foo "*bar*" foo**', '<p><strong>foo &quot;<em>bar</em>&quot; foo</strong></p>', 395],
  ['**foo**bar', '<p><strong>foo</strong>bar</p>', 396],
  ['__foo bar __', '<p>__foo bar __</p>', 397],
  ['__(__foo)', '<p>__(__foo)</p>', 398],
  ['_(__foo__)_', '<p><em>(<strong>foo</strong>)</em></p>', 399],
  ['__foo__bar', '<p>__foo__bar</p>', 400],
  ['__пристаням__стремятся', '<p>__пристаням__стремятся</p>', 401],
  ['__foo__bar__baz__', '<p><strong>foo__bar__baz</strong></p>', 402],
  ['__(bar)__.', '<p><strong>(bar)</strong>.</p>', 403],
  ['*foo [bar](/url)*', '<p><em>foo <a href="/url">bar</a></em></p>', 404],
  ['*foo\nbar*', '<p><em>foo\nbar</em></p>', 405],
  ['_foo __bar__ baz_', '<p><em>foo <strong>bar</strong> baz</em></p>', 406],
  ['_foo _bar_ baz_', '<p><em>foo <em>bar</em> baz</em></p>', 407],
  ['__foo_ bar_', '<p><em><em>foo</em> bar</em></p>', 408],
  ['*foo *bar**', '<p><em>foo <em>bar</em></em></p>', 409],
  ['*foo **bar** baz*', '<p><em>foo <strong>bar</strong> baz</em></p>', 410],
  ['*foo**bar**baz*', '<p><em>foo<strong>bar</strong>baz</em></p>', 411],
  ['*foo**bar*', '<p><em>foo**bar</em></p>', 412],
  ['***foo** bar*', '<p><em><strong>foo</strong> bar</em></p>', 413],
  ['*foo **bar***', '<p><em>foo <strong>bar</strong></em></p>', 414],
  ['*foo**bar***', '<p><em>foo<strong>bar</strong></em></p>', 415],
  ['foo***bar***baz', '<p>foo<em><strong>bar</strong></em>baz</p>', 416],
  ['foo******bar*********baz', '<p>foo<strong><strong><strong>bar</strong></strong></strong>***baz</p>', 417],
  ['*foo **bar *baz* bim** bop*', '<p><em>foo <strong>bar <em>baz</em> bim</strong> bop</em></p>', 418],
  ['*foo [*bar*](/url)*', '<p><em>foo <a href="/url"><em>bar</em></a></em></p>', 419],
  ['** is not an empty emphasis', '<p>** is not an empty emphasis</p>', 420],
  ['**** is not an empty strong emphasis', '<p>**** is not an empty strong emphasis</p>', 421],
  ['**foo [bar](/url)**', '<p><strong>foo <a href="/url">bar</a></strong></p>', 422],
  ['**foo\nbar**', '<p><strong>foo\nbar</strong></p>', 423],
  ['__foo _bar_ baz__', '<p><strong>foo <em>bar</em> baz</strong></p>', 424],
  ['__foo __bar__ baz__', '<p><strong>foo <strong>bar</strong> baz</strong></p>', 425],
  ['____foo__ bar__', '<p><strong><strong>foo</strong> bar</strong></p>', 426],
  ['**foo **bar****', '<p><strong>foo <strong>bar</strong></strong></p>', 427],
  ['**foo *bar* baz**', '<p><strong>foo <em>bar</em> baz</strong></p>', 428],
  ['**foo*bar*baz**', '<p><strong>foo<em>bar</em>baz</strong></p>', 429],
  ['***foo* bar**', '<p><strong><em>foo</em> bar</strong></p>', 430],
  ['**foo *bar***', '<p><strong>foo <em>bar</em></strong></p>', 431],
  ['**foo *bar **baz**\nbim* bop**', '<p><strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong></p>', 432],
  ['**foo [*bar*](/url)**', '<p><strong>foo <a href="/url"><em>bar</em></a></strong></p>', 433],
  ['__ is not an empty emphasis', '<p>__ is not an empty emphasis</p>', 434],
  ['____ is not an empty strong emphasis', '<p>____ is not an empty strong emphasis</p>', 435],
  ['foo ***', '<p>foo ***</p>', 436],
  ['foo *\\**', '<p>foo <em>*</em></p>', 437],
  ['foo *_*', '<p>foo <em>_</em></p>', 438],
  ['foo *****', '<p>foo *****</p>', 439],
  ['foo **\\***', '<p>foo <strong>*</strong></p>', 440],
  ['foo **_**', '<p>foo <strong>_</strong></p>', 441],
  ['**foo*', '<p>*<em>foo</em></p>', 442],
  ['*foo**', '<p><em>foo</em>*</p>', 443],
  ['***foo**', '<p>*<strong>foo</strong></p>', 444],
  ['****foo*', '<p>***<em>foo</em></p>', 445],
  ['**foo***', '<p><strong>foo</strong>*</p>', 446],
  ['*foo****', '<p><em>foo</em>***</p>', 447],
  ['foo ___', '<p>foo ___</p>', 448],
  ['foo _\\__', '<p>foo <em>_</em></p>', 449],
  ['foo _*_', '<p>foo <em>*</em></p>', 450],
  ['foo _____', '<p>foo _____</p>', 451],
  ['foo __\\___', '<p>foo <strong>_</strong></p>', 452],
  ['foo __*__', '<p>foo <strong>*</strong></p>', 453],
  ['__foo_', '<p>_<em>foo</em></p>', 454],
  ['_foo__', '<p><em>foo</em>_</p>', 455],
  ['___foo__', '<p>_<strong>foo</strong></p>', 456],
  ['____foo_', '<p>___<em>foo</em></p>', 457],
  ['__foo___', '<p><strong>foo</strong>_</p>', 458],
  ['_foo____', '<p><em>foo</em>___</p>', 459],
  ['**foo**', '<p><strong>foo</strong></p>', 460],
  ['*_foo_*', '<p><em><em>foo</em></em></p>', 461],
  ['__foo__', '<p><strong>foo</strong></p>', 462],
  ['_*foo*_', '<p><em><em>foo</em></em></p>', 463],
  ['****foo****', '<p><strong><strong>foo</strong></strong></p>', 464],
  ['____foo____', '<p><strong><strong>foo</strong></strong></p>', 465],
  ['******foo******', '<p><strong><strong><strong>foo</strong></strong></strong></p>', 466],
  ['***foo***', '<p><em><strong>foo</strong></em></p>', 467],
  ['_____foo_____', '<p><em><strong><strong>foo</strong></strong></em></p>', 468],
  ['*foo _bar* baz_', '<p><em>foo _bar</em> baz_</p>', 469],
  ['*foo __bar *baz bim__ bam*', '<p><em>foo <strong>bar *baz bim</strong> bam</em></p>', 470],
  ['**foo **bar baz**', '<p>**foo <strong>bar baz</strong></p>', 471],
  ['*foo *bar baz*', '<p>*foo <em>bar baz</em></p>', 472],
  ['*[bar*](/url)', '<p>*<a href="/url">bar*</a></p>', 473],
  ['_foo [bar_](/url)', '<p>_foo <a href="/url">bar_</a></p>', 474],
  ['*<img src="foo" title="*"/>', '<p>*&lt;img src=&quot;foo&quot; title=&quot;*&quot;/&gt;</p>', 475],
  ['**<a href="**">', '<p>**&lt;a href=&quot;**&quot;&gt;</p>', 476],
  ['__<a href="__">', '<p>__&lt;a href=&quot;__&quot;&gt;</p>', 477],
  ['*a `*`*', '<p><em>a <code>*</code></em></p>', 478],
  ['_a `_`_', '<p><em>a <code>_</code></em></p>', 479],
  ['**a<https://foo.bar/?q=**>', '<p>**a<a href="https://foo.bar/?q=**">https://foo.bar/?q=**</a></p>', 480],
  ['__a<https://foo.bar/?q=__>', '<p>__a<a href="https://foo.bar/?q=__">https://foo.bar/?q=__</a></p>', 481],
];
let pass=0, fail=0;
const fails=[];
for (const [inp, expected, num] of cases) {
  let out;
  try { out = toStr(render(clstr(inp))); } catch(e){ out='EXC:'+(e.message||e); }
  if (out===expected+'\n') { pass++; }
  else { fail++; fails.push(num+'  '+JSON.stringify(inp)+'\n    exp '+JSON.stringify(expected)+'\n    got '+JSON.stringify(out)); }
}
console.log('PASS='+pass+' FAIL='+fail);
for (const x of fails) console.log('FAIL: '+x);
